### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by object88** [go-commons/commons#7]
Even with the best of communities, communications can become strained.  I would love to see a Code of Conduct in place here from the get-go to keep things as welcome & inclusive as possible.

I know that Github has some boiler-plate stuff.  Is anything more that that required to start?

**Comment by object88** [comment]
As a starting point, there is [this COC template](https://www.contributor-covenant.org/version/1/4/code-of-conduct.md).

**Comment by bketelsen** [comment]
excellent thought, added.
